name: publish

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: install dependencies
        run: python -m pip install -r requirements.txt
        
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: render & publish
        run: ./render && ./publish
        env:
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          CF_DISTRO_ID: ${{ secrets.CF_DISTRO_ID }}
